Fix photos query for Android 11
react-native-cameraroll/react-native-cameraroll pull request #322
Opened 2021-06-27 16:43 UTC by r0b0t3d

# Summary
Fix #320 
Android 11 does not work with current implementation for paging.

## Test Plan
- Tested in Android 11 emulator

### What's required for testing (prerequisites)?
- Android 11
### What are the steps to reproduce (after prerequisites)?
- use `getPhotos` with `first` and `after` params
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a simulator ( I don't have Android 11 device)
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2021-07-19 11:43 UTC, manuelabarca commented
Any reviewers for this ?

2021-07-26 15:16 UTC, Muriet96 commented
Any reviewers for this ?

2021-07-29 23:07 UTC, Muriet96 requested changes
Sorting not working with your params

2021-07-29 23:07 UTC, Muriet96 commented on android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> +          bundle.putStringArray(ContentResolver.QUERY_ARG_SORT_COLUMNS,
```suggestion
          bundle.putString(ContentResolver.QUERY_ARG_SQL_SORT_ORDER, Images.Media.DATE_ADDED + " DESC, " + Images.Media.DATE_MODIFIED + " DESC");
```

2021-07-29 23:07 UTC, Muriet96 commented on android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> +                  new String[]{ Images.Media.DATE_ADDED, Images.Media.DATE_MODIFIED });
```suggestion
```

2021-07-29 23:07 UTC, Muriet96 commented on android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> +          bundle.putInt(ContentResolver.QUERY_ARG_SORT_DIRECTION, ContentResolver.QUERY_SORT_DIRECTION_DESCENDING);
```suggestion
```

2021-07-29 23:07 UTC, Muriet96 commented on android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> +          bundle.putStringArray(ContentResolver.QUERY_ARG_SORT_COLUMNS,
Sorting not working

2021-11-10 04:17 UTC, NhatGinnovations commented
@r0b0t3d Is there a sorting bug on Android 11?

2021-11-10 04:36 UTC, r0b0t3d commented
@NhatGinnovations It works my side. You can try then let me know if it works your side. Thanks

2021-11-10 06:26 UTC, NhatGinnovations commented
> @NhatGinnovations It works my side. You can try then let me know if it works your side. Thanks

I try to get all the photos on Android 11 and the new ones are added back at the bottom of the list. Can you tell me the cause and how to solve it?

Note: It still works as expected on Android 10 by sorting.

2021-11-25 18:15 UTC, kesha-antonov commented
Works for me
Tests on android 10 & 11

2021-11-30 13:15 UTC, r0b0t3d commented
@demedos  yes, with this PR, you can remove `requestLegacyExternalStorage`

2021-11-30 14:41 UTC, rainyer commented
Hi, good morning to all.
When will this get merged? 
I've tested the code above in Android 11 with @Muriet96 paging fixes and it works perfectly.

2021-12-03 11:21 UTC, demedos commented
This seems to be saving pictures in the Download folder instead of the camera roll. Tested on Huawei P40 lite 5G

2022-04-29 20:14 UTC, majirosstefan commented
any plans where this could be merged ?

2022-05-23 17:44 UTC, idrissakhi commented
it does not work when targetSdkVersion and compileSdkVersion is 31, if i remove the legacyScopedStorage flag from manifest i get the images paths, but it does not display anything on react-native side.

i am on React Native 0.68.2

any tips guys @manuelabarca

2022-08-18 10:07 UTC, idrissakhi commented
Resolved in v5.0.0

2022-08-18 10:07 UTC, closed without merging

2022-08-23 08:37 UTC, bartolkaruza commented
:tada: This issue has been resolved in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@react-native-camera-roll/camera-roll/v/5.0.0)
- [GitHub release](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v5.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: