feat: Return full `PhotoIdentifier` in save()
react-native-cameraroll/react-native-cameraroll pull request #569
Opened 2023-12-13 14:45 UTC by mrousavy

# Summary

**TL;DR: Adds `saveAsset(): Promise<PhotoIdentifier>` to get the full photo asset immediately after saving.**

---

This PR changes the behaviour of the native `saveToCameraRoll` function to return the full `PhotoIdentifier` instead of just the URI.

The motivation behind this is feature request #568.

This is useful if you want to append the image to state and render it immediately, e.g. in Gallery or Camera apps (such as [ShadowLens](https://mrousavy.com/projects/shadowlens)), because you can use the `id` for equality comparisons and keys, and elements like width and height are immediately available.

To not make this breaking, `save()` will still return a string (the URI), and a new method called `saveAsset()` has been introduced, which returns the full photo asset.

## Test Plan

Save a photo by calling `save()` and `saveAsset()` and compare the different return values. one is a string, one the full PhotoIdentifier.

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2023-12-14 09:30 UTC, Arjan-Zuidema commented
@mrousavy I dont rely on the unit tests (because they did not work when I became a maintainer), I usually run tests on the FabricExample to make sure everything works.

2023-12-14 09:44 UTC, mrousavy commented
Yep I think I'm done - I tested iOS and Android and both the old `save` and new `saveAsset` funcs work! :) 

I do think that the codebase is a bit tricky to work with, maybe we could tackle a Swift/Kotlin rewrite sometime in the next year and separate the components a bit cleaner. I could help with that

2023-12-14 14:09 UTC, santhoshvai commented
That would be great

2023-12-28 13:28 UTC, idrisssakhi requested changes

2023-12-28 13:28 UTC, idrisssakhi commented on jest.setup.js
> +  saveToCameraRoll: jest.fn().mockResolvedValue({ node: { image: { uri: '' } } }),
i would say () => Promise.resolve(({ node: { image: { uri: '' } } })), so it can work

2023-12-28 13:28 UTC, idrisssakhi commented on src/CameraRoll.ts
> +  static async save(
i would put a deprecation comment here so we can remove it in the future

2023-12-28 13:28 UTC, idrisssakhi commented on src/CameraRoll.ts
> +  static saveAsset(
please add the jsDoc params

2023-12-28 13:28 UTC, idrisssakhi commented on src/__mocks__/nativeInterface.ts
> +  saveToCameraRoll: jest.fn().mockResolvedValue({node: {image: {uri: ''}}}),
save feedback as previous one for the mocking

2023-12-28 13:28 UTC, idrisssakhi commented on src/__tests__/CameraRollTest.ts
> +    .mockResolvedValue({node: {image: {uri: ''}}});
same

2023-12-28 13:29 UTC, idrisssakhi commented
i think we should also update the PRs policy to only have one commit per PR eventhough we have the squash on github i find it better to have only one commit

2023-12-28 13:31 UTC, idrisssakhi commented
@mrousavy seems ok after testing, if you take the feedbacks into account we can merge it after that

2023-12-28 14:04 UTC, mrousavy commented
Done, applied your suggestions! :)

2023-12-28 14:36 UTC, merged

2023-12-29 10:44 UTC, mrousavy commented
yuhuu, thanks! let me know if there's any issues/regressions coming up :)

2024-01-02 15:08 UTC, Arjan-Zuidema commented
@idrisssakhi seems like the ci failed and no release was created

2024-01-03 12:12 UTC, bartolkaruza commented
:tada: This PR is included in version 7.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@react-native-camera-roll/camera-roll/v/7.3.0)
- [GitHub release](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v7.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: